In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
os.getcwd()

'/Users/WilliamSpagnola/Desktop'

In [3]:
#os.listdir()
dta = pd.read_csv('input.txt', dtype = str)

In [4]:
lst = pd.Series.tolist(dta)
lst[0:5]

[['010000100100'],
 ['010011111111'],
 ['000101001111'],
 ['010100011111'],
 ['111100111011']]

#### Unnest List

In [5]:
#a = [split(words) for words in lst]
# Note: Remember lists are mutable so you can append "in place" rather than using assignment 

def unnest(lst):
    unnest_lst = []
    for sublst in lst:
        for elem in sublst:
            unnest_lst.append(elem)
    return(unnest_lst)

unnest_lst = unnest(lst)

#### Split Characters

In [6]:
# from https://www.geeksforgeeks.org/python-split-string-into-list-of-characters/
def int_split(word):
    return [int(char) for char in word]

In [7]:
splt_lst = [int_split(i) for i in unnest_lst]
splt_lst[0:5]

[[0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
 [0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
 [0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1],
 [0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1]]

In [8]:
mat = np.asarray(splt_lst)
mat

array([[0, 1, 0, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 1, 1, 1]])

In [9]:
mat.shape

(999, 12)

In [145]:
gamma_bin  = (mat.sum(axis = 0) > (mat.shape[0] / 2))*1
epsilon_bin  = (mat.sum(axis = 0) < (mat.shape[0] / 2))*1

print('gamma binary:', gamma_bin)
print('epsilon binary:', epsilon_bin)

gamma binary: [1 1 0 0 0 0 1 1 1 1 1 1]
epsilon binary: [0 0 1 1 1 1 0 0 0 0 0 0]


### Boolean Gamma, Epsilon Matrices

In [152]:
gamma_bool = (mat == gamma_bin)*1
epsilon_bool = (mat == epsilon_bin)*1

print(mat[0])
print(epsilon_bin)
print(epsilon_bool[0])

[0 1 0 0 0 0 1 0 0 1 0 0]
[0 0 1 1 1 1 0 0 0 0 0 0]
[1 0 0 0 0 0 0 1 1 0 1 1]


In [15]:
z = np.arange(mat.shape[1])
#z = np.repeat(2, 12)
#z

#map()

def exp_2(x):
    return(2**x)

bin_array = np.asarray(list(map(exp_2, z)))[::-1]
bin_array

array([2048, 1024,  512,  256,  128,   64,   32,   16,    8,    4,    2,
          1])

In [20]:
gamma = np.sum(gamma_bin*bin_array)
epsilon = np.sum(epsilon_bin*bin_array)
final_answer = gamma*epsilon
print("gamma:",gamma)
print("epsilon:", epsilon)
print("final answer:", final_answer)

gamma: 3135
epsilon: 960
final answer: 3009600


## Part II

In [81]:
print(gamma_dot[0, 0])
print(mat[0])
print(bin_array)

2020
[0 1 0 0 0 0 1 0 0 1 0 0]
[2048 1024  512  256  128   64   32   16    8    4    2    1]


In [74]:
#gamma_mat = [gamma_bin == mat]*bin_array
gamma_dot = np.dot([gamma_bin == mat], bin_array)



print(gamma_dot.shape)
# a.item ?
idx = np.where(gamma_dot == np.max(gamma_dot))
#idx
print(idx)


mat[216, :]





(1, 999)
(array([0]), array([217]))


array([0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1])

In [90]:
a = np.arange(1,12 + 1).reshape(4,3)
print("a:\n", a, '\n')
b = np.array([10, 20, 30])
print("b:\n", b)


a:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

b:
 [10 20 30]


In [91]:
np.dot(a, b)

array([140, 320, 500, 680])

In [93]:
print(bin_array)
print(bin_array.shape)


[2048 1024  512  256  128   64   32   16    8    4    2    1]
(12,)


In [95]:
print(mat[0, :])
print(mat.shape)

[0 1 0 0 0 0 1 0 0 1 0 0]
(999, 12)


In [122]:
np.dot(mat[0, :], bin_array)

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [141]:
dec_bool_g = np.dot(gamma_bool, bin_array)
print(np.where(dec_bool_g  == np.max(dec_nums)))
print(gamma_bool[217,]*1)
print(dec_bool_g [217])
print(mat[217])
print(gamma_bin)


(array([217]),)
[1 1 1 1 1 1 1 1 1 0 1 1]
4091
[1 1 0 0 0 0 1 1 1 0 1 1]
[1 1 0 0 0 0 1 1 1 1 1 1]


In [156]:
print(dec_bool_e[0])
print(epsilon_bool[0])
print(bin_array)

2075
[1 0 0 0 0 0 0 1 1 0 1 1]
[2048 1024  512  256  128   64   32   16    8    4    2    1]


In [178]:
dec_bool_e = np.dot(epsilon_bool, bin_array)
print(np.where(dec_bool_e  == np.max(dec_bool_e )))
print(mat[291, ])
print(epsilon_bin)
print(epsilon_bool[291,])
print(dec_bool_e [291])


(array([291]),)
[0 0 1 1 1 1 0 0 1 0 0 1]
[0 0 1 1 1 1 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 0 1 1 0]
4086


### Convert from Binary to Decimal

In [176]:
o2_gen = np.dot(mat[217], bin_array)
print(o2_gen)
print(mat[217])
print(gamma_bin)
print(bin_array)

2048 + 1024+32+16+8+2+1

3131
[1 1 0 0 0 0 1 1 1 0 1 1]
[1 1 0 0 0 0 1 1 1 1 1 1]
[2048 1024  512  256  128   64   32   16    8    4    2    1]


3131

In [177]:
co2_gen = np.dot(mat[291], bin_array)
print(co2_gen)
print(mat[291])
print(epsilon_bin)
print(bin_array)

969
[0 0 1 1 1 1 0 0 1 0 0 1]
[0 0 1 1 1 1 0 0 0 0 0 0]
[2048 1024  512  256  128   64   32   16    8    4    2    1]


In [211]:
final_answer2 = o2_gen * co2_gen
print("final answer (part 2):", final_answer2)

#3033939 still too low? 


final answer (part 2): 3033939


In [118]:
#final_answer2 = dec_nums[872]*dec_nums[174]
#print("final answer (part 2):", final_answer2)
# Too low: 4092

final answer (part 2): 4095


In [120]:
# 4,095 is highest decimal number represented by 12 binary digits
# (note: first place is 2**0 so highest place in 12-digit sequence is 2**1
2**12 -1

4095

In [194]:
sum(arr)

2

In [198]:
np.where(arr == True)

(array([291, 461]),)

In [202]:
print(mat[291 ,])
print(mat[461 ,])
print(epsilon_bin)

[0 0 1 1 1 1 0 0 1 0 0 1]
[0 0 1 1 1 1 0 0 1 1 0 1]
[0 0 1 1 1 1 0 0 0 0 0 0]


In [207]:
print(sum(arr))
print(np.where(arr==True))

1
(array([217]),)


In [212]:
o2_gen = np.dot(mat[217], bin_array)
co2_gen = np.dot(mat[461], bin_array)
final_answer2 = o2_gen * co2_gen

In [214]:
print("o2_gen:", o2_gen)
print("co2_gen:", co2_gen)
print("final answer (part 2):", final_answer2)

o2_gen: 3131
co2_gen: 973
final answer (part 2): 3046463


In [ ]:
mat_test = np.array([[0,0,1,0,0], 
 [1,1,1,1,0], 
 [1,0,1,1,0], 
 [1,0,1,1,1], 
 [1,0,1,0,1], 
 [0,1,1,1,1], 
 [0,0,1,1,1],
 [1,1,1,0,0],
 [1,0,0,0,0], 
 [1,1,0,0,1], 
 [0,0,0,1,0], 
 [0,1,0,1,0]])


### Define Functions

In [393]:
def gen_o2(mat):
    x = np.mean(mat, axis = 0)

    #return(common)
    new_mat = mat
    
    ncols = new_mat.shape[1]
    #common = np.round(new_mat)
    #print("Common:", common, '\n\n\n')
        
    for i in range(ncols):
       # print(i)
        #print(i)
        #print(value)
 
        most_common = (np.mean(new_mat[:,i]) >= 0.5)*1
        #print("common:", most_common)
        new_mat = new_mat[new_mat[ :,i] == most_common, :]
        #print(new_mat)
        
        if new_mat.shape[0] == 1:
            return(new_mat[0])
        
def gen_co2(mat):
    x = np.mean(mat, axis = 0)

    #return(common)
    new_mat = mat
    
    ncols = new_mat.shape[1]
    #common = np.round(new_mat)
    #print("Common:", common, '\n\n\n')
        
    for i in range(ncols):
       # print(i)
        #print(i)
        #print(value)
 
        least_common = (np.mean(new_mat[:,i]) < 0.5)*1
        #print("common:", most_common)
        new_mat = new_mat[new_mat[ :,i] == least_common, :]
        #print(new_mat)
        
        if new_mat.shape[0] == 1:
            return(new_mat[0])

def to_decimal(binary):
    
    bin_digits = np.flip(2**np.arange(len(binary)))
    return(np.dot(binary, bin_digits))
    

In [354]:

1 + 4 + 16

21

In [380]:
o2_test = gen_o2(mat_test)
o2_test

array([1, 0, 1, 1, 1])

In [388]:
co2_test = gen_co2(mat_test)
co2_test 

array([0, 1, 0, 1, 0])

In [391]:
print(to_decimal(o2_test))
print(to_decimal(co2_test))
print(to_decimal(o2_test)*to_decimal(co2_test))

23
10
230


In [395]:
o2_fin = gen_02(mat)
print(o2_fin)
co2_fin = gen_c02(mat)
print(co2_fin)


[1 1 1 1 0 1 1 0 0 0 1 1]
[0 1 1 0 1 1 1 0 0 0 1 0]


In [397]:
print(to_decimal(o2_fin))
print(to_decimal(co2_fin))
print(to_decimal(o2_fin)*to_decimal(co2_fin))

3939
1762
6940518


## Lessons Learned

In [ ]:
# NOTE NESTED ARRAYS
# APPEND DOESN'T NEED ASSIGNMENT
# np.where
# np.dot

## Old Code

### Struggled Imagining For Loop

In [193]:
arr = (mat[:, 0] == epsilon_bin[0]) & (mat[:, 1] == epsilon_bin[1] ) & (mat[:, 2] == epsilon_bin[2] ) & (mat[:, 3] == epsilon_bin[3]) & (mat[:, 4] == epsilon_bin[4] ) & (mat[:, 5] == epsilon_bin[5] ) & (mat[:, 6] == epsilon_bin[6]) & (mat[:, 7] == epsilon_bin[7] ) 
