In [9]:
import numpy as np

In [25]:
lst_test = [[1,1,1,1,1],
            [1,9,9,9,1],
            [1,9,1,9,1],
            [1,9,9,9,1],
            [1,1,1,1,1]]
a = np.array(lst_test)
print("A:\n {}\n\n Shape: {}".format(a,a.shape))
#print(a.shape)

A:
 [[1 1 1 1 1]
 [1 9 9 9 1]
 [1 9 1 9 1]
 [1 9 9 9 1]
 [1 1 1 1 1]]

 Shape: (5, 5)


### Iterate through a single round of octupi
While loop continues along as there are octupi who are flashing

In [17]:
def octo_iter(a):
    
    # a: matrix of dumbo octupi 
    
    # Initialize Variables
    #iteration = 0;
    nrow, ncol = a.shape
    a1 = a + 1
    x, y = np.where(a1 == 10)

    # Don't think I need this
    #a_flash = np.zeros([nrow, ncol], dtype = int)
    #a_flash[a1==10] = 1
    
    if len(x) == 0:
       # print(iteration)
        return(dict(matrix = a1, flash =0))

    # One interation of octupi (repeat for flashes )
    while len(x) > 0:     
        #print(iteration)
        #print('\nFlash:\n', (a1 >=10)*1)
        
        a2 = np.zeros([nrow, ncol], dtype = int)
        
        for m in range(len(x)):
            
                i = x[m]
                j = y[m]
                coord = [i, j]
                #print(coord)
            
                u = i-1 if (i > 0) else np.nan
                d = i + 1 if (i < nrow-1)  else np.nan
                ver = (u, d)
                #print("Vertical", ver)

                l = j-1 if (j > 0) else np.nan
                r = j+1 if (j < ncol-1) else np.nan
                hor = (l, r)
                #print("Horizontal", hor)

                diag_ul = (u, l)
                diag_ur = (u, r)
                diag_dl = (d, l)
                diag_dr = (d, r)
                diag = [diag_ul, diag_ur, diag_dl, diag_dr]
          
                 # An octopus can only flash at most once per step
                for n in ver:
                   # print([n, j])
                    
                    if (np.isnan(n) == False):
                       # print("check", [n,j])
                        if (a1[n,j] < 10):
                          #  print("plus 1 vertical")

                            a2[n, j] = a2[n, j] + 1
                            
                for n in hor:
                    if (np.isnan(n) == False): 
                       # print("check", [i,n])
                        if (a1[i,n] < 10):
                            #print("plus 1 vertical")
      
                            a2[i, n] = a2[i, n] + 1
                            
                for n in diag:
                   # print("diag")
                    #print("n", n)
                    if (sum(np.isnan(n)*1) == 0):
                        #print(a1[n])
                        if a1[n] < 10:
                            a2[n] = a2[n] + 1
        #a_flash[a2 >= 10] = 1
        at = a1 + a2
        #print(at)
        #print(a1)
        #print(a2)
        new_flash = ((at > 9)*(a1 <= 9) )
        x, y = np.where(new_flash)
        
        #print(len(x))
        #a_total_steps =  a_total_steps + a2
        a1 = at
        #print('\na2\')
        #print("\na1\n", a1)
        #iteration = iteration + 1
        
    #Reset flashes back to zer0
    #a_final = at

    #print(at)
        #a_final = at
        #print(a_final)
    n_flash = sum(sum((at >= 10)*1))
    at[at >= 10] = 0
    #print(a_total_steps)
    #print(at)
    return(dict(matrix = at, flash = n_flash))

#x = octo_iter(a)
#print(x['matrix'])
#print(x['flash'])

### Function to simulate multiple rounds: octo_sim( )

In [12]:
def octo_sim(x, n):
    
    #input 
    ## x: array of octopi, numbers represent levels
    ## n: number of iterations to run octo_iter() function
    
    octo_lst = []
             
    for i in range(n):
        y = octo_iter(x)
        octo_lst.append(y)
        x = y['matrix']
        if np.all(x == np.zeros(list(x.shape), dtype = int)):
            print("All the Octopi Flashed at the same time in Round ", i+1)
            return(i+1)
    
    flash_lst = []
    for i in octo_lst:
        flash_lst.append(i['flash'])

    return(sum(flash_lst))


### Test octo_sim( )

In [18]:
x_lst =  [[5,4,8,3,1,4,3,2,2,3],
          [2,7,4,5,8,5,4,7,1,1],
          [5,2,6,4,5,5,6,1,7,3],
          [6,1,4,1,3,3,6,1,4,6],
          [6,3,5,7,3,8,5,4,7,8],
          [4,1,6,7,5,2,4,6,4,5],
          [2,1,7,6,8,4,1,7,2,1],
          [6,8,8,2,8,8,1,1,3,4],
          [4,8,4,6,8,4,8,5,5,4],
          [5,2,8,3,7,5,1,5,2,6]]

x = np.array(x_lst)


print("Number of Flashes")
print('10 Iterations:', octo_sim(x, 10))
print("100 Iterations:", octo_sim(x, 100))

Number of Flashes
10 Iterations: 204
100 Iterations: 1656


In [19]:
octo_sim(x, 200)

All the Octopi Flashed at the same time in Round  195


195

## Part 1: Real Input

### Read in Text file

In [23]:
text_lst = []
with open("input11.txt") as f:
    lines = f.readlines()
    for line in lines:
        num_row = [num for num in line.strip()]
        text_lst.append(num_row)
        
x_part1 = np.array(text_lst, dtype = int)
print(x_part1)
print(x_part1.shape)

[[6 6 1 7 1 1 3 5 8 4]
 [6 5 4 4 2 1 8 6 3 8]
 [5 4 5 7 3 3 1 4 8 8]
 [1 1 3 5 6 7 5 5 8 7]
 [1 2 2 1 3 5 3 2 1 6]
 [1 8 1 1 1 2 4 3 7 8]
 [1 3 8 7 8 6 4 3 6 8]
 [4 4 2 7 6 3 7 2 6 2]
 [6 7 7 8 6 4 5 4 8 6]
 [3 6 8 2 1 4 6 7 4 5]]
(10, 10)


In [24]:
octo_sim(x_part1, 100)

1599

## Part 2

In [22]:
octo_sim(x_part1, 1000)

All the Octopi Flashed at the same time in Round  418


418

## New python Functions

- **np.any( )**: return *True* if any element in the array is true
- **np.all( )**: return *True* if all elements in the array are true

## Notes
 - Remember to account for zero indexing when running through iterations (Hint: add one)
 - Remember that range() does not include last number.  Range(9) goes from 0 to 8.