In [6]:
import numpy as np

In [7]:
lst = "on x=10..12,y=10..12,z=10..12\non x=11..13,y=11..13,z=11..13\noff x=9..11,y=9..11,z=9..11\non x=10..10,y=10..10,z=10..10"

In [8]:
io = []
coord = []

for line in lst.split("\n"):
    io.append(line.split()[0])
    coord.append(line.split()[1])

In [63]:
mat = np.zeros((20, 20, 20), dtype = int)
mat[10:12+1, 10:12+1, 10:12+1] = 1
#mat.shape
mat

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [10]:
for i in range(mat.shape[0]):
    for j in range(mat.shape[1]):
        for k in range(mat.shape[2]):
            if mat[i, j, k] == 1:
                 print(i,j, k) 
            else:
                pass

10 10 10
10 10 11
10 10 12
10 11 10
10 11 11
10 11 12
10 12 10
10 12 11
10 12 12
11 10 10
11 10 11
11 10 12
11 11 10
11 11 11
11 11 12
11 12 10
11 12 11
11 12 12
12 10 10
12 10 11
12 10 12
12 11 10
12 11 11
12 11 12
12 12 10
12 12 11
12 12 12


In [14]:
coord_split = [x.split(',') for x in coord]

In [25]:
# r m in re.finditer(r"\w+ly\b", text):
import re
z = re.findall("\\d+..\\d+", coord_split[0][0])
print(z)

['10..12']


In [31]:
coord_split

[['x=10..12', 'y=10..12', 'z=10..12'],
 ['x=11..13', 'y=11..13', 'z=11..13'],
 ['x=9..11', 'y=9..11', 'z=9..11'],
 ['x=10..10', 'y=10..10', 'z=10..10']]

In [85]:
coord_mat

array([[[10, 12],
        [10, 12],
        [10, 12]],

       [[11, 13],
        [11, 13],
        [11, 13]],

       [[ 9, 11],
        [ 9, 11],
        [ 9, 11]],

       [[10, 10],
        [10, 10],
        [10, 10]]])

In [128]:
coord_lst = []
for row in coord_split:
    elem_lst = []
    for elem in row:
        elem_lst.append(re.findall("\\d+..\\d+", elem)[0].split(".."))
    coord_lst.append(elem_lst)

idx_lst= []

for row in coord_lst:
    idx_row = []
    for i in row:
        i_num = np.array(i, dtype = int)
        #print(i_num)
        idx_row.append( slice(i_num[0], i_num[1]+1, 1))
    idx_lst.append(idx_row)
    
idx_lst  

[[slice(10, 13, 1), slice(10, 13, 1), slice(10, 13, 1)],
 [slice(11, 14, 1), slice(11, 14, 1), slice(11, 14, 1)],
 [slice(9, 12, 1), slice(9, 12, 1), slice(9, 12, 1)],
 [slice(10, 11, 1), slice(10, 11, 1), slice(10, 11, 1)]]

In [137]:
mat = np.zeros((20, 20, 20), dtype = int)
for i, idx in enumerate(idx_lst):
    if io[i] == 'on':
        mat[idx[0], idx[1], idx[2]] = 1
    else:
        mat[idx[0], idx[1], idx[2]] = 0
mat

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [138]:
np.sum(mat==1)

39

##  Test 2

In [54]:
coord_mat.shape

(4, 3, 2)

In [52]:
io

['on', 'on', 'off', 'on']

##  Run Reactor Reboot

In [84]:
# create arrays
reboot_lst = []

for i, cubes in enumerate(coord_mat):
    reboot = []
    for x in range(cubes[0][0], cubes[0][1]+1):
        for y in range(cubes[1][0], cubes[1][1]+1):
            for z in range(cubes[2][0], cubes[2][1]+1):
                #print(x, y, z)
                reboot.append([x, y, z])
    reboot_lst.append(reboot)

reboot_lst[1]
    #reboot_mat = np.array(reboot_lst, dtype = int)

[[11, 11, 11],
 [11, 11, 12],
 [11, 11, 13],
 [11, 12, 11],
 [11, 12, 12],
 [11, 12, 13],
 [11, 13, 11],
 [11, 13, 12],
 [11, 13, 13],
 [12, 11, 11],
 [12, 11, 12],
 [12, 11, 13],
 [12, 12, 11],
 [12, 12, 12],
 [12, 12, 13],
 [12, 13, 11],
 [12, 13, 12],
 [12, 13, 13],
 [13, 11, 11],
 [13, 11, 12],
 [13, 11, 13],
 [13, 12, 11],
 [13, 12, 12],
 [13, 12, 13],
 [13, 13, 11],
 [13, 13, 12],
 [13, 13, 13]]