### Load Test Data

In [1]:
import numpy as np

In [2]:
coord_lst = [[[0,9], [5,9]],
             [[8,0], [0,8]],
             [[9,4], [3,4]],
             [[2,2], [2,1]],
             [[7,0], [7,4]],
             [[6,4], [2,0]],
             [[0,9], [2,9]],
             [[3,4], [1,4]],
             [[0,0], [8,8]],
             [[5,5], [8,2]]]

In [7]:
coord_test = np.array(coord_lst)
coord_test.shape

(10, 2, 2)

In [420]:
print(coord_test[0], "\n")
print("[0,0]:",coord_test[0,0,0])
print("[0,1]:",coord_test[0,0,1])
print("[1,0]:",coord_test[0,1,0])
print("[1,1]:",coord_test[0,1,1])

[[0 9]
 [5 9]] 

[0,0]: 0
[0,1]: 9
[1,0]: 5
[1,1]: 9


In [421]:
# Print second row of each grid (i.e. end point)
coord_test[:,1, :]

array([[5, 9],
       [0, 8],
       [3, 4],
       [2, 1],
       [7, 4],
       [2, 0],
       [2, 9],
       [1, 4],
       [8, 8],
       [8, 2]])

In [422]:
for x,y in coord_test:
    print("x: {}, y {}".format(x,y))

x: [0 9], y [5 9]
x: [8 0], y [0 8]
x: [9 4], y [3 4]
x: [2 2], y [2 1]
x: [7 0], y [7 4]
x: [6 4], y [2 0]
x: [0 9], y [2 9]
x: [3 4], y [1 4]
x: [0 0], y [8 8]
x: [5 5], y [8 2]


In [423]:
# Find horizontal and vertical lines
row_idx = np.sum((coord_test[:,0,:] == coord_test[:,1,:])*1, axis = 1)
row_idx

array([1, 0, 1, 1, 1, 0, 1, 1, 0, 0])

In [424]:
# Keep rows for coord 1
coord1 = coord_test[row_idx == 1, :, :]
coord1

array([[[0, 9],
        [5, 9]],

       [[9, 4],
        [3, 4]],

       [[2, 2],
        [2, 1]],

       [[7, 0],
        [7, 4]],

       [[0, 9],
        [2, 9]],

       [[3, 4],
        [1, 4]]])

In [425]:
grid = np.zeros([9, 9], dtype = int)
grid

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [426]:
new_grid = grid
new_grid[3:1, 4] = 1 
print(new_grid)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [427]:
coord1[0]
coord1[0].shape
coord1[0][0, 1]

9

### Add Coordinate Function

In [428]:
def add_coord(x, n = 10):
    new_grid = np.zeros([n,n], dtype = int)
    #x is a 2 by 2 array
    hor = abs(x[1,0] - x[0,0])
    ver = abs(x[1,1] - x[0,1])
    if hor > 0:
        str_pt = min(x[1,0], x[0,0]) 
        end_pt = max(x[1,0], x[0,0]) +1
        new_grid[ x[0,1], str_pt:end_pt,  ] = 1 
        return(new_grid)
    elif ver > 0:
        str_pt = min(x[0,1], x[1,1])
        end_pt = max(x[0,1], x[1,1])  + 1
        new_grid[str_pt:end_pt, x[1,0]  ] = 1 
        return(new_grid)

In [429]:
grid_lst = []
for x in coord1:
    print(x)
    grid_lst.append(add_coord(x))

[[0 9]
 [5 9]]
[[9 4]
 [3 4]]
[[2 2]
 [2 1]]
[[7 0]
 [7 4]]
[[0 9]
 [2 9]]
[[3 4]
 [1 4]]


In [430]:
vent_grid = np.sum(grid_lst, axis = 0)
print(vent_grid)
print(vent_grid.shape)

[[0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 1 1 2 1 1 1 2 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [2 2 2 1 1 1 0 0 0 0]]
(10, 10)


In [431]:
(vent_grid >= 2)*1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0]])

In [432]:
print("Test Answer (part 1): ", np.sum(vent_grid >= 2))

Test Answer (part 1):  5


## Part 1: Actual Answer 

In [433]:
#import os
#os.listdir()
import re

In [434]:
### Important string methods
# split
# join
# replace

#'405,945 -> 780,945'.split(' -> ')

## Input Data

In [31]:
line_list = []
with open("input5.txt") as f:  
    for line in f.readlines():
        line_list.append(line.strip())
f.close()

coord_list = []
for i, x in enumerate(line_list): 
    z = x.split(' -> ')
    block = []
    for nums in z:
        w = nums.split(',')
        block.append(w)
    coord_list.append(block)

coord_list[0:5]
coord_real = np.array(coord_list, dtype = int)
coord_real.shape

(500, 2, 2)

In [436]:
coord_real[0:5]

array([[[405, 945],
        [780, 945]],

       [[253, 100],
        [954, 801]],

       [[518, 300],
        [870, 300]],

       [[775, 848],
        [ 20, 848]],

       [[586, 671],
        [469, 671]]])

In [437]:
coord[0:5]

array([[[0, 9],
        [5, 9]],

       [[8, 0],
        [0, 8]],

       [[9, 4],
        [3, 4]],

       [[2, 2],
        [2, 1]],

       [[7, 0],
        [7, 4]]])

In [438]:
grid_lst = []
for x in coord_real:
    #print(x)
    grid_lst.append(add_coord(x, n = 1000))

## Forgot to filter out diagonal rows

In [439]:
vent_grid = np.sum(grid_lst, axis = 0)
#vent_grid

#print("Final Answer (part 1): ", np.sum(vent_grid >= 2))

Final Answer (part 1):  18302


In [167]:
# Find horizontal and vertical lines
row_idx = np.sum((coord_real[:,0,:] == coord_real[:,1,:])*1, axis = 1)
coord_real_1 = coord_real[row_idx == 1, :, :]
coord_real_1

array([[[405, 945],
        [780, 945]],

       [[518, 300],
        [870, 300]],

       [[775, 848],
        [ 20, 848]],

       [[586, 671],
        [469, 671]],

       [[598,  20],
        [900,  20]],

       [[561, 456],
        [ 67, 456]],

       [[357, 873],
        [407, 873]],

       [[480, 247],
        [774, 247]],

       [[230, 895],
        [230, 709]],

       [[696, 821],
        [696, 198]],

       [[501, 461],
        [ 85, 461]],

       [[884,  88],
        [884, 922]],

       [[140, 780],
        [146, 780]],

       [[795, 208],
        [273, 208]],

       [[256, 185],
        [256, 525]],

       [[282, 196],
        [282,  85]],

       [[701, 133],
        [ 18, 133]],

       [[623, 548],
        [623, 573]],

       [[212, 944],
        [934, 944]],

       [[948, 504],
        [948, 502]],

       [[551, 613],
        [551,  27]],

       [[ 62,  54],
        [452,  54]],

       [[915, 851],
        [915, 290]],

       [[924, 843],
        [924, 

In [170]:
coord_real_1.shape

(349, 2, 2)

In [61]:
grid_lst = []
for i, x in enumerate(coord_real_1):
    if((i + 1) % 20 == 0):
        print((i+1))
    grid_lst.append(add_coord(x, n = 1000))

# First guess; 18,302
# 7,438?

NameError: name 'coord_real_1' is not defined

# Final Answer (Part 1)

In [180]:
vent_grid = np.sum(grid_lst, axis = 0)
print("Test Answer (part 1): ", np.sum(vent_grid >= 2))

Test Answer (part 1):  7438


In [ ]:
 
#     if (block[1, 0] > block[0,0]) & (block[1, 1] > block[0,1]):
#         x_range = range(block[0,0], block[1,0]+1, 1 )
#         y_int = block[0, 1] - block[0,0]
#     elif (block[1, 0] > block[0,0]) & (block[1, 1] < block[0,1]):
#         x_range = range(block[1,0], block[0,0]-1, sign_x)
#         y_int =  block[1, 1] 
#         print(y_int)
#     else:
#         x_range = range(block[1,0], block[0,0]+1, 1 )
#         y_int = block[1, 1] - block[1,0]

### Diagonal Lines Function

In [43]:
def diag_step(block, grid):
   
    if block[1,0] > block[0,0]:
        start_x = block[0,0]
        end_x   = block[1,0]
        start_y = block[0,1]
        end_y   = block[1,1]
        sign_y = 1 if block[1,1] > block[0,1] else -1
    
    else:
        start_x = block[1,0]
        end_x   = block[0,0]
        start_y = block[1,1]
        end_y   = block[0,1]
        sign_y = -1 if block[1,1] > block[0,1] else 1
    
    x_range = np.arange(start_x, end_x + 1, 1 )
    y_range = np.arange(start_y, end_y + sign_y, sign_y )
    
    for i,x in enumerate(x_range):
        print(x_range[i], y_range[i])
        grid[y_range[i], x_range[i] ] = 1
    return(grid)

2 0
3 1
4 2
5 3
6 4


array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### Test diag_step function

In [47]:
#Set up for function

grid = np.zeros([10,10], dtype = int)
#block = np.array([[8,0],[0, 8]])
#block = np.array([[0,0],[8, 8]])
#block = np.array([[1,1],[9, 9]])
#block = np.array([[1,2],[5, 6]])
#block = np.array([[0,8],[8, 0]])
#block = np.array([[5, 5],[8, 2]])
block = np.array([[1,1],[3,3]])
block = np.array([[9,7],[7,9]])
block = np.array([[6, 4], [2,0]])
print(block)
x =diag_step(block,grid)
print(x)
print(x.shape)

[[6 4]
 [2 0]]
2 0
3 1
4 2
5 3
6 4
[[0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
(10, 10)


In [49]:
test_mat = np.zeros([10,5], dtype = int)
test_mat[0,2] = 9
test_mat


array([[0, 0, 9, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# note () around conditions if more than 1

def add_coord_diag(x, n = 10):
    new_grid = np.zeros([n,n], dtype = int)
    
    #x is a 2 by 2 array
    hor_mov = x[0,0] - x[1,0]
    ver_mov = x[0,1] - x[1,1]

    if (hor_mov != 0) & (ver_mov == 0):
        #print('Hor')
        str_pt = min(x[1,0], x[0,0]) 
        end_pt = max(x[1,0], x[0,0]) +1
        new_grid[ x[0,1], str_pt:end_pt,  ] = 1 
        return(new_grid)
    elif (ver_mov != 0) & (hor_mov == 0):
       # print('Vert')
        str_pt = min(x[0,1], x[1,1])
        end_pt = max(x[0,1], x[1,1])  + 1
        new_grid[str_pt:end_pt, x[1,0]  ] = 1 
        return(new_grid)
    elif (ver_mov != 0) & (hor_mov != 0):
        #print("Diagonal")
        #print(x)
        new_grid = diag_step(x, new_grid)
        return(new_grid)

In [26]:
grid_lst = []
for x in coord_test:
    print(x)
    grid_lst.append(add_coord_diag(x))
    #add_coord_diag(x)

[[0 9]
 [5 9]]
Hor
[[8 0]
 [0 8]]
Diagonal
0 8
1 7
2 6
3 5
4 4
5 3
6 2
7 1
8 0
[[9 4]
 [3 4]]
Hor
[[2 2]
 [2 1]]
Vert
[[7 0]
 [7 4]]
Vert
[[6 4]
 [2 0]]
Diagonal
2 0
3 1
4 2
5 3
6 4
[[0 9]
 [2 9]]
Hor
[[3 4]
 [1 4]]
Hor
[[0 0]
 [8 8]]
Diagonal
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
[[5 5]
 [8 2]]
Diagonal
5 5
6 4
7 3
8 2


In [27]:
grid_lst[5]

array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
ans = np.sum(grid_lst, axis = 0)
ans

array([[1, 0, 1, 0, 0, 0, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 2, 0, 0],
       [0, 0, 2, 0, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 2, 0, 2, 0, 0],
       [0, 1, 1, 2, 3, 1, 3, 2, 1, 1],
       [0, 0, 0, 1, 0, 2, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [2, 2, 2, 1, 1, 1, 0, 0, 0, 0]])

In [29]:
np.sum(ans>= 2)

12

### Final Answer (Part 2):

In [32]:
coord_real.shape
np.max(coord_real)

989

In [38]:
grid_lst_fin = []
for x in coord_real:
    grid_lst_fin.append(add_coord_diag(x, 1000))

Hor
Diagonal
253 100
254 101
255 102
256 103
257 104
258 105
259 106
260 107
261 108
262 109
263 110
264 111
265 112
266 113
267 114
268 115
269 116
270 117
271 118
272 119
273 120
274 121
275 122
276 123
277 124
278 125
279 126
280 127
281 128
282 129
283 130
284 131
285 132
286 133
287 134
288 135
289 136
290 137
291 138
292 139
293 140
294 141
295 142
296 143
297 144
298 145
299 146
300 147
301 148
302 149
303 150
304 151
305 152
306 153
307 154
308 155
309 156
310 157
311 158
312 159
313 160
314 161
315 162
316 163
317 164
318 165
319 166
320 167
321 168
322 169
323 170
324 171
325 172
326 173
327 174
328 175
329 176
330 177
331 178
332 179
333 180
334 181
335 182
336 183
337 184
338 185
339 186
340 187
341 188
342 189
343 190
344 191
345 192
346 193
347 194
348 195
349 196
350 197
351 198
352 199
353 200
354 201
355 202
356 203
357 204
358 205
359 206
360 207
361 208
362 209
363 210
364 211
365 212
366 213
367 214
368 215
369 216
370 217
371 218
372 219
373 220
374 221
375 222
376

491 273
492 274
493 275
494 276
495 277
496 278
497 279
498 280
499 281
500 282
501 283
502 284
503 285
504 286
505 287
506 288
507 289
508 290
509 291
510 292
511 293
512 294
513 295
514 296
515 297
516 298
517 299
518 300
519 301
520 302
521 303
522 304
523 305
524 306
525 307
526 308
527 309
528 310
529 311
530 312
531 313
532 314
533 315
534 316
535 317
536 318
537 319
538 320
539 321
540 322
541 323
542 324
543 325
544 326
545 327
546 328
547 329
548 330
549 331
550 332
551 333
552 334
553 335
554 336
555 337
556 338
557 339
558 340
559 341
560 342
561 343
562 344
563 345
564 346
565 347
566 348
567 349
568 350
569 351
570 352
571 353
572 354
573 355
574 356
575 357
576 358
577 359
578 360
579 361
580 362
581 363
582 364
583 365
584 366
585 367
586 368
587 369
588 370
589 371
590 372
591 373
592 374
593 375
594 376
595 377
596 378
597 379
598 380
599 381
600 382
601 383
602 384
603 385
604 386
605 387
606 388
607 389
608 390
609 391
610 392
611 393
612 394
613 395
614 396
615 397


172 102
173 103
174 104
175 105
176 106
177 107
178 108
179 109
180 110
181 111
182 112
183 113
184 114
185 115
186 116
187 117
188 118
189 119
190 120
191 121
192 122
193 123
194 124
195 125
196 126
197 127
198 128
199 129
200 130
201 131
202 132
203 133
204 134
205 135
206 136
207 137
208 138
209 139
210 140
211 141
212 142
213 143
214 144
215 145
216 146
217 147
218 148
219 149
220 150
221 151
222 152
223 153
224 154
225 155
226 156
227 157
228 158
229 159
230 160
231 161
232 162
233 163
234 164
235 165
236 166
237 167
238 168
239 169
240 170
241 171
242 172
243 173
244 174
245 175
246 176
247 177
248 178
249 179
250 180
251 181
252 182
253 183
254 184
255 185
256 186
257 187
258 188
259 189
260 190
261 191
262 192
263 193
264 194
265 195
266 196
267 197
268 198
269 199
270 200
271 201
272 202
273 203
274 204
275 205
276 206
277 207
278 208
279 209
280 210
281 211
282 212
283 213
284 214
285 215
286 216
287 217
288 218
289 219
290 220
291 221
292 222
293 223
294 224
295 225
296 226


687 781
688 782
689 783
690 784
691 785
692 786
693 787
694 788
695 789
696 790
697 791
698 792
699 793
700 794
701 795
702 796
703 797
704 798
705 799
706 800
707 801
708 802
709 803
710 804
711 805
712 806
713 807
714 808
715 809
716 810
717 811
718 812
719 813
720 814
721 815
722 816
723 817
724 818
725 819
726 820
727 821
728 822
729 823
730 824
731 825
732 826
733 827
734 828
735 829
736 830
737 831
738 832
739 833
740 834
741 835
742 836
743 837
744 838
745 839
746 840
747 841
748 842
749 843
750 844
751 845
752 846
753 847
754 848
755 849
756 850
757 851
758 852
759 853
760 854
761 855
762 856
763 857
764 858
765 859
766 860
767 861
768 862
769 863
770 864
771 865
772 866
773 867
774 868
775 869
776 870
777 871
778 872
779 873
780 874
781 875
782 876
783 877
784 878
785 879
786 880
787 881
788 882
789 883
790 884
791 885
792 886
793 887
794 888
795 889
796 890
797 891
798 892
799 893
800 894
801 895
802 896
803 897
804 898
805 899
806 900
807 901
808 902
809 903
810 904
811 905


362 672
363 671
364 670
365 669
366 668
367 667
368 666
369 665
370 664
371 663
372 662
373 661
374 660
375 659
376 658
377 657
378 656
379 655
380 654
381 653
382 652
383 651
384 650
385 649
386 648
387 647
388 646
389 645
390 644
391 643
392 642
393 641
394 640
395 639
396 638
397 637
398 636
399 635
400 634
401 633
402 632
403 631
404 630
405 629
406 628
407 627
408 626
409 625
410 624
411 623
412 622
413 621
414 620
415 619
416 618
417 617
418 616
419 615
420 614
421 613
422 612
423 611
424 610
425 609
426 608
427 607
428 606
429 605
430 604
431 603
432 602
433 601
434 600
435 599
436 598
437 597
438 596
439 595
440 594
441 593
442 592
443 591
444 590
445 589
446 588
447 587
448 586
449 585
450 584
451 583
452 582
453 581
454 580
455 579
456 578
457 577
458 576
459 575
460 574
461 573
462 572
463 571
464 570
465 569
466 568
467 567
468 566
469 565
470 564
471 563
472 562
473 561
474 560
475 559
476 558
477 557
478 556
479 555
480 554
481 553
482 552
483 551
484 550
485 549
486 548


332 332
333 333
334 334
335 335
336 336
337 337
338 338
339 339
340 340
341 341
342 342
343 343
344 344
345 345
346 346
347 347
348 348
349 349
350 350
351 351
352 352
353 353
354 354
355 355
356 356
357 357
358 358
359 359
360 360
361 361
362 362
363 363
364 364
365 365
366 366
367 367
368 368
369 369
370 370
371 371
372 372
373 373
374 374
375 375
376 376
377 377
378 378
379 379
380 380
381 381
382 382
383 383
384 384
385 385
386 386
387 387
388 388
389 389
390 390
391 391
392 392
393 393
394 394
395 395
396 396
397 397
398 398
399 399
400 400
401 401
402 402
403 403
404 404
405 405
406 406
407 407
408 408
409 409
410 410
411 411
412 412
413 413
414 414
415 415
416 416
417 417
418 418
419 419
420 420
421 421
422 422
423 423
424 424
425 425
426 426
427 427
428 428
429 429
430 430
431 431
432 432
433 433
434 434
435 435
436 436
437 437
438 438
439 439
440 440
441 441
442 442
443 443
444 444
445 445
446 446
447 447
448 448
449 449
450 450
451 451
452 452
453 453
454 454
455 455
456 456


519 666
520 667
521 668
522 669
523 670
524 671
525 672
526 673
527 674
528 675
529 676
530 677
531 678
532 679
533 680
534 681
535 682
536 683
537 684
538 685
539 686
540 687
541 688
542 689
543 690
544 691
545 692
546 693
547 694
548 695
549 696
550 697
551 698
552 699
553 700
554 701
555 702
556 703
557 704
558 705
559 706
560 707
561 708
562 709
563 710
564 711
565 712
566 713
567 714
568 715
569 716
570 717
571 718
572 719
573 720
574 721
575 722
576 723
577 724
578 725
579 726
580 727
581 728
582 729
583 730
584 731
585 732
586 733
587 734
588 735
589 736
590 737
591 738
592 739
593 740
594 741
595 742
596 743
597 744
598 745
599 746
600 747
601 748
602 749
603 750
604 751
605 752
606 753
607 754
608 755
609 756
610 757
611 758
612 759
613 760
614 761
615 762
616 763
617 764
618 765
619 766
620 767
621 768
622 769
623 770
624 771
625 772
626 773
627 774
628 775
629 776
630 777
631 778
632 779
633 780
634 781
635 782
636 783
637 784
638 785
639 786
640 787
641 788
642 789
643 790


436 449
437 450
438 451
439 452
440 453
441 454
442 455
443 456
444 457
445 458
446 459
447 460
448 461
449 462
450 463
451 464
452 465
453 466
454 467
455 468
456 469
457 470
458 471
459 472
460 473
461 474
462 475
463 476
464 477
465 478
466 479
467 480
468 481
469 482
470 483
471 484
472 485
473 486
474 487
475 488
476 489
477 490
478 491
479 492
480 493
481 494
482 495
483 496
484 497
485 498
486 499
487 500
488 501
489 502
490 503
491 504
492 505
493 506
494 507
495 508
496 509
497 510
498 511
499 512
500 513
501 514
502 515
503 516
504 517
505 518
506 519
507 520
508 521
509 522
510 523
511 524
512 525
513 526
514 527
515 528
516 529
517 530
518 531
519 532
520 533
521 534
522 535
523 536
524 537
525 538
526 539
527 540
528 541
529 542
530 543
531 544
532 545
533 546
534 547
535 548
536 549
537 550
538 551
539 552
540 553
541 554
542 555
543 556
544 557
545 558
546 559
547 560
548 561
549 562
550 563
551 564
552 565
553 566
554 567
555 568
556 569
557 570
558 571
559 572
560 573


668 381
669 380
670 379
671 378
672 377
673 376
674 375
675 374
676 373
677 372
678 371
679 370
680 369
681 368
682 367
683 366
684 365
685 364
686 363
687 362
688 361
689 360
690 359
691 358
692 357
693 356
694 355
695 354
696 353
697 352
698 351
699 350
700 349
701 348
702 347
703 346
704 345
705 344
706 343
707 342
708 341
709 340
710 339
711 338
712 337
713 336
714 335
715 334
716 333
717 332
718 331
719 330
720 329
721 328
722 327
723 326
724 325
725 324
726 323
727 322
728 321
729 320
730 319
731 318
732 317
733 316
734 315
735 314
736 313
737 312
738 311
739 310
740 309
741 308
742 307
743 306
744 305
745 304
746 303
747 302
748 301
749 300
750 299
751 298
752 297
753 296
754 295
755 294
756 293
757 292
758 291
759 290
760 289
761 288
762 287
763 286
764 285
765 284
766 283
767 282
768 281
769 280
770 279
771 278
772 277
773 276
774 275
775 274
776 273
777 272
778 271
779 270
780 269
781 268
782 267
783 266
784 265
785 264
786 263
787 262
788 261
789 260
790 259
791 258
792 257


198 213
199 214
200 215
201 216
202 217
203 218
204 219
205 220
206 221
207 222
208 223
209 224
210 225
211 226
212 227
213 228
214 229
215 230
216 231
217 232
218 233
219 234
220 235
221 236
222 237
223 238
224 239
225 240
226 241
227 242
228 243
229 244
230 245
231 246
232 247
233 248
234 249
235 250
236 251
237 252
238 253
239 254
240 255
241 256
242 257
243 258
244 259
245 260
246 261
247 262
248 263
249 264
250 265
251 266
252 267
253 268
254 269
255 270
256 271
257 272
258 273
259 274
260 275
261 276
262 277
263 278
264 279
265 280
266 281
267 282
268 283
269 284
270 285
271 286
272 287
273 288
274 289
275 290
276 291
277 292
278 293
279 294
280 295
281 296
282 297
283 298
284 299
285 300
286 301
287 302
288 303
289 304
290 305
291 306
292 307
293 308
294 309
295 310
296 311
297 312
298 313
299 314
300 315
301 316
302 317
303 318
304 319
305 320
306 321
307 322
308 323
309 324
310 325
311 326
312 327
313 328
314 329
315 330
316 331
317 332
318 333
319 334
320 335
321 336
322 337


78 24
79 25
80 26
81 27
82 28
83 29
84 30
85 31
86 32
87 33
88 34
89 35
90 36
91 37
92 38
93 39
94 40
95 41
96 42
97 43
98 44
99 45
100 46
101 47
102 48
103 49
104 50
105 51
106 52
107 53
108 54
109 55
110 56
111 57
112 58
113 59
114 60
115 61
116 62
117 63
118 64
119 65
120 66
121 67
122 68
123 69
124 70
125 71
126 72
127 73
128 74
129 75
130 76
131 77
132 78
133 79
134 80
135 81
136 82
137 83
138 84
139 85
140 86
141 87
142 88
143 89
144 90
145 91
146 92
147 93
148 94
149 95
150 96
151 97
152 98
153 99
154 100
155 101
156 102
157 103
158 104
159 105
160 106
161 107
162 108
163 109
164 110
165 111
166 112
167 113
168 114
169 115
170 116
171 117
172 118
173 119
174 120
175 121
176 122
177 123
178 124
179 125
180 126
181 127
182 128
183 129
184 130
185 131
186 132
187 133
188 134
189 135
190 136
191 137
192 138
193 139
194 140
195 141
196 142
197 143
198 144
199 145
200 146
201 147
202 148
203 149
204 150
205 151
206 152
207 153
208 154
209 155
210 156
211 157
212 158
213 159
214 160
21

189 834
190 833
191 832
192 831
193 830
194 829
195 828
196 827
197 826
198 825
199 824
200 823
201 822
202 821
203 820
204 819
205 818
206 817
207 816
208 815
209 814
210 813
211 812
212 811
213 810
214 809
215 808
216 807
217 806
218 805
219 804
220 803
221 802
222 801
223 800
224 799
225 798
226 797
227 796
228 795
229 794
230 793
231 792
232 791
233 790
234 789
235 788
236 787
237 786
238 785
239 784
240 783
241 782
242 781
243 780
244 779
245 778
246 777
247 776
248 775
249 774
250 773
251 772
252 771
253 770
254 769
255 768
256 767
257 766
258 765
259 764
260 763
261 762
262 761
263 760
264 759
265 758
266 757
267 756
268 755
269 754
270 753
271 752
272 751
273 750
274 749
275 748
276 747
277 746
278 745
279 744
280 743
281 742
282 741
283 740
284 739
285 738
286 737
287 736
288 735
289 734
290 733
291 732
292 731
293 730
294 729
295 728
296 727
297 726
298 725
299 724
300 723
301 722
302 721
303 720
304 719
305 718
306 717
307 716
308 715
309 714
310 713
311 712
312 711
313 710


155 524
156 523
157 522
158 521
159 520
160 519
161 518
162 517
163 516
164 515
165 514
166 513
167 512
168 511
169 510
170 509
171 508
172 507
173 506
174 505
175 504
176 503
177 502
178 501
179 500
180 499
181 498
182 497
183 496
184 495
185 494
186 493
187 492
188 491
189 490
190 489
191 488
192 487
193 486
194 485
195 484
196 483
197 482
198 481
199 480
200 479
201 478
202 477
203 476
204 475
205 474
206 473
207 472
208 471
209 470
210 469
211 468
212 467
213 466
214 465
215 464
216 463
217 462
218 461
219 460
220 459
221 458
222 457
223 456
224 455
225 454
226 453
227 452
228 451
229 450
230 449
231 448
232 447
233 446
234 445
235 444
236 443
237 442
238 441
239 440
240 439
241 438
242 437
243 436
244 435
245 434
246 433
247 432
248 431
249 430
250 429
251 428
252 427
253 426
254 425
255 424
256 423
257 422
258 421
259 420
260 419
261 418
262 417
263 416
264 415
265 414
266 413
267 412
268 411
269 410
270 409
271 408
272 407
273 406
274 405
275 404
276 403
277 402
278 401
279 400


502 562
503 561
504 560
505 559
506 558
507 557
508 556
509 555
510 554
511 553
512 552
513 551
514 550
515 549
516 548
517 547
518 546
519 545
520 544
521 543
522 542
523 541
524 540
525 539
526 538
527 537
528 536
529 535
530 534
531 533
532 532
533 531
534 530
535 529
536 528
537 527
538 526
539 525
540 524
541 523
542 522
543 521
544 520
545 519
546 518
547 517
548 516
549 515
550 514
551 513
552 512
553 511
554 510
555 509
556 508
557 507
558 506
559 505
560 504
561 503
562 502
563 501
564 500
565 499
566 498
567 497
568 496
569 495
570 494
571 493
572 492
573 491
574 490
575 489
576 488
577 487
578 486
579 485
580 484
581 483
582 482
583 481
584 480
585 479
586 478
587 477
588 476
589 475
590 474
591 473
592 472
593 471
594 470
595 469
596 468
597 467
598 466
599 465
600 464
601 463
602 462
603 461
604 460
605 459
606 458
607 457
608 456
609 455
610 454
611 453
612 452
613 451
614 450
615 449
616 448
617 447
618 446
619 445
620 444
621 443
622 442
623 441
624 440
625 439
626 438


421 406
422 407
423 408
424 409
425 410
426 411
427 412
428 413
429 414
430 415
431 416
432 417
433 418
434 419
435 420
436 421
437 422
438 423
439 424
440 425
441 426
442 427
443 428
444 429
445 430
446 431
447 432
448 433
449 434
450 435
451 436
452 437
453 438
454 439
455 440
456 441
457 442
458 443
459 444
460 445
461 446
462 447
463 448
464 449
465 450
466 451
467 452
468 453
469 454
470 455
471 456
472 457
473 458
474 459
475 460
476 461
477 462
478 463
479 464
480 465
481 466
482 467
483 468
484 469
485 470
486 471
487 472
488 473
489 474
490 475
491 476
492 477
493 478
494 479
495 480
496 481
497 482
498 483
499 484
500 485
501 486
502 487
503 488
504 489
505 490
506 491
507 492
508 493
509 494
510 495
511 496
512 497
513 498
514 499
515 500
516 501
517 502
518 503
519 504
520 505
521 506
522 507
523 508
524 509
525 510
526 511
527 512
528 513
529 514
530 515
531 516
532 517
533 518
534 519
535 520
536 521
537 522
538 523
539 524
540 525
541 526
542 527
543 528
544 529
545 530


728 320
729 319
730 318
731 317
732 316
733 315
734 314
735 313
736 312
737 311
738 310
739 309
740 308
741 307
742 306
743 305
744 304
745 303
746 302
747 301
748 300
749 299
750 298
751 297
752 296
753 295
754 294
755 293
756 292
757 291
758 290
759 289
760 288
761 287
Vert
Diagonal
219 903
220 902
221 901
222 900
223 899
224 898
225 897
226 896
227 895
228 894
229 893
230 892
231 891
232 890
233 889
234 888
235 887
236 886
237 885
238 884
239 883
240 882
241 881
242 880
243 879
244 878
245 877
246 876
247 875
248 874
249 873
250 872
251 871
252 870
253 869
254 868
255 867
256 866
257 865
258 864
259 863
260 862
261 861
262 860
263 859
264 858
265 857
266 856
267 855
268 854
269 853
270 852
271 851
272 850
273 849
274 848
275 847
276 846
277 845
278 844
279 843
280 842
281 841
282 840
283 839
284 838
285 837
286 836
287 835
288 834
289 833
290 832
291 831
292 830
293 829
294 828
295 827
296 826
297 825
298 824
299 823
300 822
301 821
302 820
303 819
304 818
305 817
306 816
307 815
30

330 407
331 406
332 405
333 404
334 403
335 402
336 401
337 400
338 399
339 398
340 397
341 396
342 395
343 394
344 393
345 392
346 391
347 390
348 389
349 388
350 387
351 386
352 385
353 384
354 383
355 382
356 381
357 380
358 379
359 378
360 377
361 376
362 375
363 374
364 373
365 372
366 371
367 370
368 369
369 368
370 367
371 366
372 365
373 364
374 363
375 362
376 361
377 360
378 359
379 358
380 357
381 356
382 355
383 354
384 353
385 352
386 351
387 350
388 349
389 348
390 347
391 346
392 345
393 344
394 343
395 342
396 341
397 340
398 339
399 338
400 337
401 336
402 335
403 334
404 333
405 332
406 331
407 330
408 329
409 328
410 327
411 326
412 325
413 324
414 323
415 322
416 321
417 320
418 319
419 318
420 317
421 316
422 315
423 314
424 313
425 312
426 311
427 310
428 309
429 308
430 307
431 306
432 305
433 304
434 303
435 302
436 301
437 300
438 299
439 298
440 297
441 296
442 295
443 294
444 293
445 292
446 291
447 290
448 289
449 288
450 287
451 286
452 285
453 284
454 283


KeyboardInterrupt: 

In [34]:
grid_vent2 = np.sum(grid_lst_fin, axis = 0)

In [37]:
np.sum(grid_vent2 >= 2)
#21488 = Too High 
#21406 Bingo!!! 

21406

# Old Code

In [ ]:
#np.set_printoptions(threshold=np.inf)
#np.set_printoptions(threhold=1000)
#vent_grid.shape

### Old Diagonal  Step Function

In [498]:
# #1,1 -> 3,3 covers points 1,1, 2,2, and 3,3.
# grid = np.zeros([10,10], dtype = int)
# #block = np.array([[1,1], [3,3]])
# block = np.array([[3, 3], [1,1]])
# block = np.array([[5, 5], [8, 2]])
# block = np.array([[8,0],[0 8]])
# print(block )

# def diag_step(coord, grid):
#     new_grid = grid
#     str_pt = coord[0]
#     step_dir = coord[1] - coord[0]
#     x_sign = 1 if step_dir[0] >= 0 else -1
#     y_sign = 1 if step_dir[1] >= 0 else -1 
#     print(step_dir)
#     x_steps = range(0,(abs(step_dir[0]) +1)*-x_sign,-x_sign)
#     print(x_steps)
#     y_steps = range(0, (abs(step_dir[1])+1 )*y_sign,y_sign)
#     steps = np.max(abs(step_dir))+1

#     #print("y steps", y_steps)
#     for i in range(steps):
#         x_loc_cur = x_steps[i] + str_pt[0]
#         y_loc_cur = y_steps[i] + str_pt[1]
#         print(x_loc_cur, y_loc_cur)
#         #print(new_grid.shape[0] - x_loc_cur)
#         new_grid[ x_loc_cur, new_grid.shape[0] - y_loc_cur] = 1
# #         print("x: {} y: {}".format(x_loc_cur, y_loc_cur))   
#     return(new_grid)

# diag_step(block, grid)
#for i in range(0,-3, -1): 
#    print(i)#

[[5 5]
 [8 2]]
[ 3 -3]
range(0, -4, -1)
5 5
4 4
3 3
2 2


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])