In [1]:
import numpy as np
import os

In [2]:
test_mat = np.array([['#','.','.','#','.'],
                ['#','.','.','.','.'],
                ['#','#','.','.','#'],
                ['.','.','#','.','.'],
                ['.','.','#','#','#']])

In [3]:
decode = []
with open('input20_test.txt') as f:
    lines = f.readlines()
    for l in lines:
        for char in l.strip():
            decode.append(char)

arr = np.array(decode[1:len(decode)])
arr[0:5]

array(['.', '.', '#', '.', '#'], dtype='<U1')

In [77]:
def check(mat, i, j):
    l = i+1
    r = i-1
    u =j+1
    d = j-1

    z = [mat[l,u], mat[i, u], mat[r, u], 
         mat[l, j], mat[i, j], mat[r, j], 
         mat[l, d], mat[i, d], mat[r, d]]
    return(z)

In [78]:
ind = check(test_mat, 2, 2)
ind

['.', '.', '.', '#', '.', '.', '.', '#', '.']

##  Run Image through Image Enhancement Algorithm

In [73]:
bin_dict = {'.': 0, '#': 1}
print(bin_dict)
bin_exp = np.arange(len(ind))[::-1] # create vector of numbers in 
print(bin_exp)
bin_arr = np.array([bin_dict[code] for code in ind])
print(bin_arr)
dec_arr = bin_arr*(2**bin_exp)
print(dec_arr)
dec_sum = sum(dec_arr)
print(dec_sum)

# Better line
np.arange(8,0, -1)


{'.': 0, '#': 1}
[8 7 6 5 4 3 2 1 0]
[0 0 0 1 0 0 0 1 0]
[ 0  0  0 32  0  0  0  2  0]
34


array([8, 7, 6, 5, 4, 3, 2, 1])

###  Function to enhance image 

In [84]:
def enhance(x):
    bin_dict = {'.': 0, '#': 1} #dictionary code for binary
    bin_arr = np.array([bin_dict[code] for code in x]) # convert codes to binary array
    dec_arr = bin_arr*(2**np.arange(len(x)-1, 0-1, -1))  # exponentiate to get decimal array
    return(sum(dec_arr)) # return sum of decimal array
enhance(ind)
#len(ind)

34

array([ 0,  0,  0, 32,  0,  0,  0,  2,  0])

In [9]:
code_idx = np.sum(bin_arr*(2**bin_exp))

In [64]:
arr[code_idx]

'#'

In [ ]:
# def mat_pad(mat):
#         np.concat()

In [20]:
test_mat

array([['#', '.', '.', '#', '.'],
       ['#', '.', '.', '.', '.'],
       ['#', '#', '.', '.', '#'],
       ['.', '.', '#', '.', '.'],
       ['.', '.', '#', '#', '#']], dtype='<U1')

In [58]:
test_mat_pad.shape

(7, 7)

In [44]:
#row pad
row_pad = np.array([['.']*test_mat.shape[1]])
test_mat_rowpad = np.concatenate((row_pad, test_mat, row_pad), axis = 0)
col_pad = np.array([['.']*test_mat_rowpad.shape[0]]).T
col_pad.shape
test_mat_pad = np.concatenate((col_pad, test_mat_rowpad, col_pad), axis = 1)
test_mat_pad

array([['.', '.', '.', '.', '.', '.', '.'],
       ['.', '#', '.', '.', '#', '.', '.'],
       ['.', '#', '.', '.', '.', '.', '.'],
       ['.', '#', '#', '.', '.', '#', '.'],
       ['.', '.', '.', '#', '.', '.', '.'],
       ['.', '.', '.', '#', '#', '#', '.'],
       ['.', '.', '.', '.', '.', '.', '.']], dtype='<U1')

In [86]:
check_list = []

for i in range(1,test_mat_pad.shape[0]-1):
    for j in range(1,test_mat_pad.shape[1]-1):
        #print(test_mat_pad[i,j])
        #print(i, j)
        check_list.append(check(test_mat_pad, i, j))
        
np.array(check_list).shape
check_list[0:5]

[['.', '.', '.', '#', '#', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '#', '#', '.'],
 ['.', '#', '.', '.', '.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '#', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.', '.', '.', '#', '.']]

##  Pseudo Code for Enhancement Algorithm

In [ ]:
# Run numbers to enhancement algorithm

# 1) pad image  matrix with 0 ('.') -> pad_image()
# 2) look at 3x3 image matrix around each pixel -> scan_pixel()
# 3) Convert each list from scan_pixel to number -> convert_pixels()
# 4) Run numbers from convert_pixels through image enhance function -> enhance_img()
# 5) return pixesl from enhance_img() as enhanced image matrix 

## Array Sub-selection

In [24]:
mat[2:4, 0:5]

array([['#', '#', '.', '.', '#'],
       ['.', '.', '#', '.', '.']], dtype='<U1')

In [26]:
mat[2:4][0:5]

array([['#', '#', '.', '.', '#'],
       ['.', '.', '#', '.', '.']], dtype='<U1')

In [28]:
mat[2:3][0:4]

array([['#', '#', '.', '.', '#']], dtype='<U1')

In [29]:
mat[2][0:4]

array(['#', '#', '.', '.'], dtype='<U1')