In [1]:
import os 
import numpy as np
import pandas as pd
#os.listdir()

In [6]:
test_lst = []

with open("input8_test.txt") as f:
    lines = f.readlines()
    
    for l in lines:
        test_lst.append(l.strip().replace('|', '').split())
    f.close()
print(test_lst)

X = pd.DataFrame(test_lst)
X.head()

0        1       2       3        4       5       6       7       8   \
0       be  cfbegad  cbdgef  fgaecd     cgeb   fdcge  agebfd   fecdb   fabcd   
1   edbfga    begcd     cbg      gc  gcadebf   fbgde  acbgfd   abcde  gfcbed   
2   fgaebd       cg   bdaec   gdafb   agbcfd  gdcbef   bgcad    gfac     gcb   
3   fbegcd      cbd  adcefb   dageb     afcb      bc   aefdc   ecdab  fgdeca   
4  aecbfdg      fbg      gf   bafeg    dbefa    fcge   gcbea  fcaegb  dgceab   

        9        10       11       12     13  
0      edb  fdgacbe    cefdb   cefbgd   gcbe  
1     gfec   fcgedb      cgb  dgebacf     gc  
2  cdgabef       cg       cg   fdcagb    cbg  
3  fcdbega   efabcd    cedba   gadfec     cb  
4   fcbdga     gecf  egdcabf      bgf  bfgea

In [40]:
check = pd.concat([X.iloc[0].rename('char'), X.iloc[0].apply(len).rename('char_len')], axis = 1)

check.loc[check.char_len == 2, 'char_replace'] = "cf"
check.loc[check.char_len == 4, 'char_replace'] = "bcdf"
check.loc[check.char_len == 3, "char_replace"] = "acf"
check.loc[check.char_len == 7, "char_replace"] = "abcdefg"

check.loc[check.char_len == 2, 'num_guess'] = "1"
check.loc[check.char_len == 4, "num_guess"] = "4"
check.loc[check.char_len == 7, "num_guess"] = "8"
check.loc[check.char_len == 3, "num_guess"] = "7"
check.loc[check.char_len == 6, "num_guess"] = "0, 6, 9"
check.loc[check.char_len == 5, "num_guess"] = "2, 3, 5"


check['char_str'] =check['char'].apply(lambda x: ''.join(sorted(x)))
    
check

char  char_len char_replace num_guess char_str
0        be         2           cf         1       be
1   cfbegad         7      abcdefg         8  abcdefg
2    cbdgef         6          NaN   0, 6, 9   bcdefg
3    fgaecd         6          NaN   0, 6, 9   acdefg
4      cgeb         4         bcdf         4     bceg
5     fdcge         5          NaN   2, 3, 5    cdefg
6    agebfd         6          NaN   0, 6, 9   abdefg
7     fecdb         5          NaN   2, 3, 5    bcdef
8     fabcd         5          NaN   2, 3, 5    abcdf
9       edb         3          acf         7      bde
10  fdgacbe         7      abcdefg         8  abcdefg
11    cefdb         5          NaN   2, 3, 5    bcdef
12   cefbgd         6          NaN   0, 6, 9   bcdefg
13     gcbe         4         bcdf         4     bceg

### Notes
b = (c, f)
e = (c, f)
d = a
cg = (b, d)

In [63]:
# X_lst = []
# Y_lst = []
# test_lst = []
# with open("input8_test.txt") as f:
    
#     lines = f.readlines()
    
#     for l in lines:
#         test_lst.append(l.strip().split("|"))
#         z = l.strip().split('|')
#         X_lst.append(z[0].split())
#         Y_lst.append(z[1].split())
        
#     f.close()
# X_lst

# X = pd.DataFrame(X_lst)
# Y = pd.DataFrame(Y_lst)
# print(X)
# print(Y)

         0        1        2        3        4        5       6       7  \
0       be  cfbegad   cbdgef   fgaecd     cgeb    fdcge  agebfd   fecdb   
1   edbfga    begcd      cbg       gc  gcadebf    fbgde  acbgfd   abcde   
2   fgaebd       cg    bdaec    gdafb   agbcfd   gdcbef   bgcad    gfac   
3   fbegcd      cbd   adcefb    dageb     afcb       bc   aefdc   ecdab   
4  aecbfdg      fbg       gf    bafeg    dbefa     fcge   gcbea  fcaegb   
5    fgeab       ca   afcebg  bdacfeg   cfaedg    gcfdb    baec  bfadeg   
6    dbcfg      fgd  bdegcaf     fgec   aegbdf   ecdfab   fbedc   dacgb   
7   bdfegc   cbegaf    gecbf   dfcage    bdacg       ed    bedf     ced   
8   egadfb   cdbfeg     cegd    fecab      cgb  gbdefca      cg  fgcdab   
9    gcafb      gcf  dcaebfg    ecagb       gf   abcdeg    gaef  cafbge   

         8        9  
0    fabcd      edb  
1   gfcbed     gfec  
2      gcb  cdgabef  
3   fgdeca  fcdbega  
4   dgceab   fcbdga  
5    bafgc      acf  
6   gdcebf       gf 

In [83]:
z = np.zeros([10, 10], dtype = int)

for col in X:

    z[col] = X[col].apply(lambda x: len(x))
    #print(z)
print(z)


[[2 6 6 6 7 5 5 6 6 5]
 [7 5 2 3 3 2 3 6 6 3]
 [6 3 5 6 2 6 7 5 4 7]
 [6 2 5 5 5 7 4 6 5 5]
 [4 7 6 4 5 6 6 5 3 2]
 [5 5 6 2 4 5 6 2 7 6]
 [6 6 5 5 5 4 5 4 2 4]
 [5 5 4 5 6 6 5 3 6 6]
 [5 6 3 6 6 5 6 7 5 5]
 [3 4 7 7 6 3 2 5 5 6]]


array([[ True, False, False, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False,  True, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False,  True, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False]])

In [101]:
a = np.char.asarray(X)
a[z == 2] = 1
a[z == 4] = 4
a[z == 7] = 3
a[z == 8] = 7

A = pd.DataFrame(a, dtype = str)
A

0           1           2          3           4           5  \
0       b'1'  b'cfbegad'   b'cbdgef'  b'fgaecd'        b'3'    b'fdcge'   
1       b'3'    b'begcd'        b'1'      b'gc'  b'gcadebf'        b'1'   
2  b'fgaebd'       b'cg'    b'bdaec'   b'gdafb'        b'1'   b'gdcbef'   
3  b'fbegcd'        b'1'   b'adcefb'   b'dageb'     b'afcb'        b'3'   
4       b'4'        b'3'       b'gf'       b'4'    b'dbefa'     b'fcge'   
5   b'fgeab'       b'ca'   b'afcebg'       b'1'        b'4'    b'gcfdb'   
6   b'dbcfg'      b'fgd'  b'bdegcaf'    b'fgec'   b'aegbdf'        b'4'   
7  b'bdfegc'   b'cbegaf'        b'4'  b'dfcage'    b'bdacg'       b'ed'   
8  b'egadfb'   b'cdbfeg'     b'cegd'   b'fecab'      b'cgb'  b'gbdefca'   
9   b'gcafb'        b'4'        b'3'       b'3'       b'gf'   b'abcdeg'   

           6          7           8           9  
0  b'agebfd'   b'fecdb'    b'fabcd'      b'edb'  
1  b'acbgfd'   b'abcde'   b'gfcbed'     b'gfec'  
2       b'3'    b'gfac'        b'4'        b'3'  
3       b'4'   b'ecdab'   b'fgdeca'  b'fcdbega'  
4   b'gcbea'  b'fcaegb'   b'dgceab'        b'1'  
5    b'baec'       b'1'        b'3'      b'acf'  
6   b'fbedc'       b'4'        b'1'        b'4'  
7    b'bedf'     b'ced'  b'adcbefg'    b'gebcd'  
8      b'cg'       b'3'    b'egfdb'    b'bfceg'  
9       b'1'  b'cafbge'    b'fdbac'   b'fegbdc'

In [162]:
#
len0 = X[0].apply(len)
a = pd.concat([X[0].rename('char'), len0.rename('char_len')], axis = 1)

#df.rename(index={0: "x", 1: "y", 2: "z"})
a['char_replace'] = ""
a['num_guess'] = ""
#a[a.char_len == 2]['char_replace'] = "cf"
#a[a.char == 4]['char_replace'] = "bcdf"
#a

# loc is annoying
a.loc[a.char_len == 2, 'char_replace'] = "cf"
a.loc[a.char_len == 4, 'char_replace'] = "bcdf"
a.loc[a.char_len == 3, "char_replace"] = "acf"
a.loc[a.char_len == 7, "char_replace"] = "abcdef"
a.loc[a.char_len == 2, 'num_guess'] = "1"
a.loc[a.char_len == 7, "num_guess"] = "8"
a.loc[a.char_len == 6, "num_guess"] = "0, 6, 9"
a.loc[a.char_len == 5, "num_guess"] = "2, 3, 5"

a
# 0, 6, 9: 6 (missing 1)

char  char_len char_replace num_guess
0       be         2           cf         1
1   edbfga         6                0, 6, 9
2   fgaebd         6                0, 6, 9
3   fbegcd         6                0, 6, 9
4  aecbfdg         7       abcdef         8
5    fgeab         5                2, 3, 5
6    dbcfg         5                2, 3, 5
7   bdfegc         6                0, 6, 9
8   egadfb         6                0, 6, 9
9    gcafb         5                2, 3, 5

## Wire Code
- 1 = 2 wires
- 4 = 4 wires
- 7 = 3 wires
- 8 = 7 wires

## Python Tips
 - iterrows( ): to iterate along rows of pandas DataFrame