In [4]:
import pandas as pd
import numpy as np
import os

In [5]:
os.getcwd()
#os.listdir()

'/Users/WilliamSpagnola/Desktop'

In [6]:
# help from https://www.pythontutorial.net/python-basics/python-read-text-file/

#with open('readme.txt') as f:
#    lines = f.readlines()


# & https://stackoverflow.com/questions/1767513/how-to-read-first-n-lines-of-a-file

#N = 10
#with open("file.txt", "a") as file:  # the a opens it in append mode
#   for i in range(N):
#        line = next(file).strip()
#        print(line)



In [7]:
n = 1
with open('input4.txt') as f:
    for i in range(n):
        lines = next(f).strip()
f.close()

x = lines.split(',')
nums = np.array(x, dtype = 'int32')
nums


array([31, 88, 35, 24, 46, 48, 95, 42, 18, 43, 71, 32, 92, 62, 97, 63, 50,
        2, 60, 58, 74, 66, 15, 87, 57, 34, 14,  3, 54, 93, 75, 22, 45, 10,
       56, 12, 83, 30,  8, 76,  1, 78, 82, 39, 98, 37, 19, 26, 81, 64, 55,
       41, 16,  4, 72,  5, 52, 80, 84, 67, 21, 86, 23, 91,  0, 68, 36, 13,
       44, 20, 69, 40, 90, 96, 27, 77, 38, 49, 94, 47,  9, 65, 28, 59, 79,
        6, 29, 61, 53, 11, 17, 73, 99, 25, 89, 51,  7, 33, 85, 70],
      dtype=int32)

In [3]:
bingo_card = []
bingo_card_list = []
count = 0
with open('input4.txt') as f:
    for i,line in enumerate(f):
        if i >= 2:        
            if (i - 7) % 6 == 0:
                bingo_card_list.append(bingo_card)
                bingo_card = []
            else:
                line2 = line.strip() 
                row = [int(i) for i in line2.split()]

                bingo_card.append(row)
f.close()            
# Note: strip method removes carriage returns ('\n')

    #count += 1
   # line2 = 
   # if count >= 1:
        #lines = next(f).strip()
    #    print(lines)

In [9]:
#x = np.loadtxt(bingo_card_list)
#np.set_printoptions(threshold=1000)
#print(x)
len(bingo_card_list)
#x = np.array(bingo_card_list)
len(bingo_card_list[0])

5

In [10]:
mat = np.empty([5, 5,99])
mat[:] = np.nan
mat

array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
  

In [11]:
mat = np.asarray(bingo_card_list)
mat.shape

(99, 5, 5)

In [12]:
print(mat[0, 1])
print('skip')
print(mat[0])
print('skip')
print(mat[98])

[47  9 94 10 86]
skip
[[50 83  3 31 16]
 [47  9 94 10 86]
 [61 22 53 46 74]
 [77 41 79 55 62]
 [97 78 43 73 40]]
skip
[[86 48 70 56 67]
 [68  7 73 55 10]
 [38 82 65 22 62]
 [51  2 34 17 53]
 [47  0 28 39 83]]


In [13]:
mat[0]

array([[50, 83,  3, 31, 16],
       [47,  9, 94, 10, 86],
       [61, 22, 53, 46, 74],
       [77, 41, 79, 55, 62],
       [97, 78, 43, 73, 40]])

In [14]:
# pandas read_csv() gets confused
#test = pd.read_csv('input4.txt')
#test

### Check Bingo Cards

In [15]:
def check_cards(mat):
    row_check_vec = np.sum(mat, axis = 1)
    col_check_vec = np.sum(mat, axis = 0)
    check_vec = np.concatenate((row_check_vec, col_check_vec), axis = 0)
    #print(check_vec)
    if np.max(check_vec)== 5:
        #print('Bingo')
        return(int(1)) 
    else:
        return(int(0))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]]


1

#### Test Check Cards Function

In [ ]:
# Test check_cards
x = np.concatenate((np.zeros([4, 5], dtype = 'int32'), np.ones([1, 5], dtype = 'int32')), axis = 0)
print(x)
check = check_cards(x)
check

### Load Test Arrays

In [16]:
num_test = np.array([7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1])

cards_test = np.array(
[[[22, 13, 17, 11,  0],
  [ 8,  2, 23,  4, 24],
  [21,  9, 14, 16,  7],
  [ 6, 10,  3, 18,  5],
  [ 1, 12, 20, 15, 19]],

 [[ 3, 15,  0,  2, 22],
  [ 9, 18, 13, 17,  5],
  [19,  8,  7, 25, 23],
  [20, 11, 10, 24,  4],
  [14, 21, 16, 12,  6]],

 [[14, 21, 17, 24,  4],
  [10, 16, 15,  9, 19],
  [18,  8, 23, 26, 20],
  [22, 11, 13,  6,  5],
  [ 2,  0, 12,  3,  7]]]
)

In [17]:
cards_test.shape

(3, 5, 5)

In [18]:
num_test

array([ 7,  4,  9,  5, 11, 17, 23,  2,  0, 14, 21, 24, 10, 16, 13,  6, 15,
       25, 12, 22, 18, 20,  8, 19,  3, 26,  1])

### Play Bingo Function

In [19]:
def play_bingo(nums, cards):
    
    card_step = np.zeros(cards.shape, dtype = 'int32')
    cur_cards = card_step
    
    for round, num in enumerate(nums):
          
        print('round:', round + 1)
        print('\tnumber:', num)
        
        card_step = (cards == num)*1
        cur_cards = cur_cards + card_step

        for i, marks in enumerate(cur_cards):
            
            bingo_check = check_cards(marks)
            print('\tbingo check {}: {}'.format(i,bingo_check))
            
            if bingo_check == 1:
                print('Bingo!')
                return([round, num, cards[i], marks])

round: 1
	number: 7
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 2
	number: 4
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 3
	number: 9
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 4
	number: 5
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 5
	number: 11
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 6
	number: 17
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 7
	number: 23
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 8
	number: 2
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 9
	number: 0
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 10
	number: 14
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 11
	number: 21
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
round: 12
	number: 24
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 1
Bingo!


#### Test Play Bingo Function

In [20]:
rnd, num, crd, mkr = play_bingo(num_test, cards_test)
print('Round:\n', rnd)
print('\nWinning Number:\n', num)
print('\nWinning Card:\n', crd)
print('\nMarkers:\n',mkr)

Round:
 11

Winning Number:
 24

Winning Card:
 [[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]

Markers:
 [[1 1 1 1 1]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 1]
 [1 1 0 0 1]]


In [21]:
sum(crd[mrk==0])*num

NameError: name 'mrk' is not defined

## Part 1: Real Answer

In [22]:
 rnd, num, crd, mkr = play_bingo(nums, mat)


round: 1
	number: 31
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
	bingo check 3: 0
	bingo check 4: 0
	bingo check 5: 0
	bingo check 6: 0
	bingo check 7: 0
	bingo check 8: 0
	bingo check 9: 0
	bingo check 10: 0
	bingo check 11: 0
	bingo check 12: 0
	bingo check 13: 0
	bingo check 14: 0
	bingo check 15: 0
	bingo check 16: 0
	bingo check 17: 0
	bingo check 18: 0
	bingo check 19: 0
	bingo check 20: 0
	bingo check 21: 0
	bingo check 22: 0
	bingo check 23: 0
	bingo check 24: 0
	bingo check 25: 0
	bingo check 26: 0
	bingo check 27: 0
	bingo check 28: 0
	bingo check 29: 0
	bingo check 30: 0
	bingo check 31: 0
	bingo check 32: 0
	bingo check 33: 0
	bingo check 34: 0
	bingo check 35: 0
	bingo check 36: 0
	bingo check 37: 0
	bingo check 38: 0
	bingo check 39: 0
	bingo check 40: 0
	bingo check 41: 0
	bingo check 42: 0
	bingo check 43: 0
	bingo check 44: 0
	bingo check 45: 0
	bingo check 46: 0
	bingo check 47: 0
	bingo check 48: 0
	bingo check 49: 0
	bingo check 50: 0
	bingo check 51: 0
	

	bingo check 95: 0
	bingo check 96: 0
	bingo check 97: 0
	bingo check 98: 0
round: 13
	number: 92
	bingo check 0: 0
	bingo check 1: 0
	bingo check 2: 0
	bingo check 3: 0
	bingo check 4: 0
	bingo check 5: 0
	bingo check 6: 0
	bingo check 7: 0
	bingo check 8: 0
	bingo check 9: 0
	bingo check 10: 0
	bingo check 11: 0
	bingo check 12: 0
	bingo check 13: 0
	bingo check 14: 0
	bingo check 15: 0
	bingo check 16: 0
	bingo check 17: 0
	bingo check 18: 0
	bingo check 19: 0
	bingo check 20: 0
	bingo check 21: 0
	bingo check 22: 0
	bingo check 23: 0
	bingo check 24: 0
	bingo check 25: 0
	bingo check 26: 0
	bingo check 27: 0
	bingo check 28: 0
	bingo check 29: 0
	bingo check 30: 0
	bingo check 31: 0
	bingo check 32: 0
	bingo check 33: 0
	bingo check 34: 0
	bingo check 35: 0
	bingo check 36: 0
	bingo check 37: 0
	bingo check 38: 0
	bingo check 39: 0
	bingo check 40: 0
	bingo check 41: 0
	bingo check 42: 0
	bingo check 43: 0
	bingo check 44: 0
	bingo check 45: 0
	bingo check 46: 0
	bingo check 47: 0


	bingo check 64: 0
	bingo check 65: 0
	bingo check 66: 1
Bingo!


In [23]:
print('Round:\n', rnd)
print('\nWinning Number:\n', num)
print('\nWinning Card:\n', crd)
print('\nMarkers:\n',mkr)

Round:
 21

Winning Number:
 66

Winning Card:
 [[84 78  3 44 96]
 [59 86 70 80 48]
 [93 88 52 43 61]
 [95 66 46 62 58]
 [ 5 25  6 85 99]]

Markers:
 [[0 0 0 0 0]
 [0 0 0 0 1]
 [0 1 0 1 0]
 [1 1 1 1 1]
 [0 0 0 0 0]]


In [24]:
nums[0:22]

array([31, 88, 35, 24, 46, 48, 95, 42, 18, 43, 71, 32, 92, 62, 97, 63, 50,
        2, 60, 58, 74, 66], dtype=int32)

In [25]:
mat[67] 

array([[66, 40, 33, 10, 52],
       [38, 30, 99, 79, 60],
       [75, 72, 59,  2, 53],
       [20, 83, 43, 76, 44],
       [48, 46, 63, 15, 84]])

In [26]:
nums[0:22]

array([31, 88, 35, 24, 46, 48, 95, 42, 18, 43, 71, 32, 92, 62, 97, 63, 50,
        2, 60, 58, 74, 66], dtype=int32)

In [27]:
mat[66]

array([[84, 78,  3, 44, 96],
       [59, 86, 70, 80, 48],
       [93, 88, 52, 43, 61],
       [95, 66, 46, 62, 58],
       [ 5, 25,  6, 85, 99]])

In [28]:
nums[21]

66

In [29]:
num*(sum(crd[mkr==0]))

67716

In [30]:
nums[0:rnd]

array([31, 88, 35, 24, 46, 48, 95, 42, 18, 43, 71, 32, 92, 62, 97, 63, 50,
        2, 60, 58, 74], dtype=int32)

### Iterate through bingo cards (dimension x of x,y,z)

In [32]:
for i,cards in enumerate(cards_test):
    print("i:", i)
    print(cards)

i: 0
[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
i: 1
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
i: 2
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]


## Lose bingo

In [33]:
def lose_bingo(nums, cards):
    
    n_cards = cards.shape[0]
    card_step = np.zeros(cards.shape, dtype = 'int32')
    cur_cards = card_step
    bingo_check_cards = np.zeros(  n_cards)
    
    # Call numbers
    for round, num in enumerate(nums):
          
        print('round:', round + 1)
        print('number:', num)
        
        card_step = (cards == num)*1
        cur_cards = cur_cards + card_step

        # Cycle through cards
        for i, marks in enumerate(cur_cards):
            
            bingo_check = check_cards(marks)
            bingo_check_cards[i] = bingo_check
            #print('\tbingo check {}: {}'.format(i,bingo_check))
            
        n_card_wins = np.sum(bingo_check_cards)
        print("Wins: {} Left: {} Total: {}".format(n_card_wins,   n_cards - n_card_wins, n_cards))
        if n_card_wins == (n_cards - 1):
            print(bingo_check_cards)
            last_card = np.where(bingo_check_cards == 0)[0][0] # losing card index number
        if n_card_wins == (n_cards):
            #Note: Need to Make sure this is last winning card, hence last_card index
            return([round, num, cards[last_card], cur_cards[last_card], last_card])
        

### Part 2: Test

In [34]:
rnd, num, crd, mkr, crd_idx = lose_bingo(num_test, cards_test)


round: 1
number: 7
Wins: 0.0 Left: 3.0 Total: 3
round: 2
number: 4
Wins: 0.0 Left: 3.0 Total: 3
round: 3
number: 9
Wins: 0.0 Left: 3.0 Total: 3
round: 4
number: 5
Wins: 0.0 Left: 3.0 Total: 3
round: 5
number: 11
Wins: 0.0 Left: 3.0 Total: 3
round: 6
number: 17
Wins: 0.0 Left: 3.0 Total: 3
round: 7
number: 23
Wins: 0.0 Left: 3.0 Total: 3
round: 8
number: 2
Wins: 0.0 Left: 3.0 Total: 3
round: 9
number: 0
Wins: 0.0 Left: 3.0 Total: 3
round: 10
number: 14
Wins: 0.0 Left: 3.0 Total: 3
round: 11
number: 21
Wins: 0.0 Left: 3.0 Total: 3
round: 12
number: 24
Wins: 1.0 Left: 2.0 Total: 3
round: 13
number: 10
Wins: 1.0 Left: 2.0 Total: 3
round: 14
number: 16
Wins: 2.0 Left: 1.0 Total: 3
[1. 0. 1.]
round: 15
number: 13
Wins: 3.0 Left: 0.0 Total: 3


In [35]:
print("Round:", rnd)
print("\nNumber:", num)
print("\nCard:\n", crd)
print("\nMarker:\n",mkr)
print("\nCard Index: ", crd_idx)

Round: 14

Number: 13

Card:
 [[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]

Marker:
 [[0 0 1 1 0]
 [1 0 1 1 1]
 [0 0 1 0 1]
 [0 1 1 1 1]
 [1 1 1 0 0]]

Card Index:  1


In [36]:
num*np.sum(crd[mkr==0])

1924

### Part 2: Actual

In [37]:
rnd, num, crd, mkr, crd_idx = lose_bingo(nums, mat)


round: 1
number: 31
Wins: 0.0 Left: 99.0 Total: 99
round: 2
number: 88
Wins: 0.0 Left: 99.0 Total: 99
round: 3
number: 35
Wins: 0.0 Left: 99.0 Total: 99
round: 4
number: 24
Wins: 0.0 Left: 99.0 Total: 99
round: 5
number: 46
Wins: 0.0 Left: 99.0 Total: 99
round: 6
number: 48
Wins: 0.0 Left: 99.0 Total: 99
round: 7
number: 95
Wins: 0.0 Left: 99.0 Total: 99
round: 8
number: 42
Wins: 0.0 Left: 99.0 Total: 99
round: 9
number: 18
Wins: 0.0 Left: 99.0 Total: 99
round: 10
number: 43
Wins: 0.0 Left: 99.0 Total: 99
round: 11
number: 71
Wins: 0.0 Left: 99.0 Total: 99
round: 12
number: 32
Wins: 0.0 Left: 99.0 Total: 99
round: 13
number: 92
Wins: 0.0 Left: 99.0 Total: 99
round: 14
number: 62
Wins: 0.0 Left: 99.0 Total: 99
round: 15
number: 97
Wins: 0.0 Left: 99.0 Total: 99
round: 16
number: 63
Wins: 0.0 Left: 99.0 Total: 99
round: 17
number: 50
Wins: 0.0 Left: 99.0 Total: 99
round: 18
number: 2
Wins: 0.0 Left: 99.0 Total: 99
round: 19
number: 60
Wins: 0.0 Left: 99.0 Total: 99
round: 20
number: 58
W

In [38]:
print("Round:", rnd)
print("\nNumber:", num)
print("\nCard:\n", crd)
print("\nMarker:\n",mkr)
print("\nCard Index: ", crd_idx)

Round: 85

Number: 6

Card:
 [[96 59 72  6 38]
 [60 70 76 82 46]
 [47 53 51 64 98]
 [44 25 69 81 33]
 [73 52 10 74 55]]

Marker:
 [[1 1 1 1 1]
 [1 0 1 1 1]
 [1 0 0 1 1]
 [1 0 1 1 0]
 [0 1 1 1 1]]

Card Index:  31


In [43]:
print("Final Answer: {}".format(num*np.sum(crd[mkr==0])))

Final Answer: 1830


##  Old Code

In [1]:
#f.readlines()

In [2]:
# n = 1
# with open('input4.txt') as f:
#     for i in range(n):
#         lines = next(f).strip()
# f.close()

#print(lines)
# byte_lines = lines.encode()
# print("Byte Lines: {} \n".format(byte_lines))
# x = []


# for i in byte_lines:
#     x.append(i)
    
# x_arr = np.array(x)
# x_arr
#Why is x_arr difference?